"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os

from pathlib import Path
from dotenv import load_dotenv
from decimal import Decimal

BASE_DIR = Path(__file__).resolve().parent.parent.parent

load_dotenv(
    dotenv_path=BASE_DIR / ".env",
    override=False,
)

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip()

if not SECRET_KEY:
    raise ValueError(
        "La variable DJANGO_SECRET_KEY debe estar configurada."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "127.0.0.1,localhost",
    ).split(",")
    if host.strip()
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.test_cases.apps.TestCasesConfig",
    "apps.pep.apps.PepConfig",
    "apps.aer_test_case.apps.AerTestCaseConfig",
    "apps.msp_qa.apps.MspQaConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Configuración documental.
MAX_UPLOAD_MB = int(
    os.getenv(
        "MAX_UPLOAD_MB",
        "100",
    )
)

if MAX_UPLOAD_MB <= 0:
    raise ValueError(
        "MAX_UPLOAD_MB debe ser mayor que cero."
    )

DATA_UPLOAD_MAX_MEMORY_SIZE = (
    MAX_UPLOAD_MB
    * 1024
    * 1024
)

FILE_UPLOAD_MAX_MEMORY_SIZE = (
    MAX_UPLOAD_MB
    * 1024
    * 1024
)


# Configuración de Claude.
ANTHROPIC_API_KEY = os.getenv(
    "ANTHROPIC_API_KEY",
    "",
).strip()

CLAUDE_MODEL = os.getenv(
    "CLAUDE_MODEL",
    "",
).strip()

MAX_TOKENS = int(
    os.getenv(
        "MAX_TOKENS",
        "8192",
    )
)

CLAUDE_TIMEOUT_SECONDS = int(
    os.getenv(
        "CLAUDE_TIMEOUT_SECONDS",
        "120",
    )
)

if MAX_TOKENS <= 0:
    raise ValueError(
        "MAX_TOKENS debe ser mayor que cero."
    )

if CLAUDE_TIMEOUT_SECONDS <= 0:
    raise ValueError(
        "CLAUDE_TIMEOUT_SECONDS debe ser mayor que cero."
    )


# Tarifas configurables. Un valor cero indica que el costo
# todavía no ha sido configurado.
CLAUDE_INPUT_USD_PER_MTOK = Decimal(
    os.getenv(
        "CLAUDE_INPUT_USD_PER_MTOK",
        "0",
    )
)

CLAUDE_OUTPUT_USD_PER_MTOK = Decimal(
    os.getenv(
        "CLAUDE_OUTPUT_USD_PER_MTOK",
        "0",
    )
)
LOG_LEVEL = os.getenv(
    "DJANGO_LOG_LEVEL",
    "INFO",
).upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": (
                "%(asctime)s %(levelname)s "
                "%(name)s %(message)s"
            ),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "loggers": {
        "apps.test_cases": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "apps.msp_qa": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

TEST_CASES_RESULT_TTL_SECONDS = int(
    (
        os.getenv(
            "TEST_CASES_RESULT_TTL_SECONDS",
            "1800",
        )
        or "1800"
    ).strip()
)

if TEST_CASES_RESULT_TTL_SECONDS <= 0:
    raise ValueError(
        "TEST_CASES_RESULT_TTL_SECONDS debe ser mayor que cero."
    )

PEP_ANALYSIS_TTL_SECONDS = int(
    (
        os.getenv(
            "PEP_ANALYSIS_TTL_SECONDS",
            "1800",
        )
        or "1800"
    ).strip()
)

PEP_RESULT_TTL_SECONDS = int(
    (
        os.getenv(
            "PEP_RESULT_TTL_SECONDS",
            "1800",
        )
        or "1800"
    ).strip()
)

if PEP_ANALYSIS_TTL_SECONDS <= 0:
    raise ValueError(
        "PEP_ANALYSIS_TTL_SECONDS debe ser mayor que cero."
    )

if PEP_RESULT_TTL_SECONDS <= 0:
    raise ValueError(
        "PEP_RESULT_TTL_SECONDS debe ser mayor que cero."
    )


# Configuración de Azure DevOps para la matriz MSP_QA.
AZURE_DEVOPS_ORG_URL = os.getenv(
    "AZURE_DEVOPS_ORG_URL",
    "",
).strip()

AZURE_DEVOPS_PAT = os.getenv(
    "AZURE_DEVOPS_PAT",
    "",
).strip()

AZURE_DEVOPS_TIMEOUT_SECONDS = int(
    (
        os.getenv(
            "AZURE_DEVOPS_TIMEOUT_SECONDS",
            "30",
        )
        or "30"
    ).strip()
)

if AZURE_DEVOPS_TIMEOUT_SECONDS <= 0:
    raise ValueError(
        "AZURE_DEVOPS_TIMEOUT_SECONDS debe ser mayor que cero."
    )

# Proporción de horas de QA respecto al total del proyecto.
# La descripción de Azure DevOps registra las horas de todos los
# roles; la matriz MSP_QA registra únicamente la porción de QA.

# Credenciales de Google. Al dejarse vacia se usa key.json en la
# raiz del proyecto.
GOOGLE_CREDENTIALS_FILE = os.getenv(
    "GOOGLE_CREDENTIALS_FILE",
    "",
).strip()


# Vigencia del catálogo de bloques en caché. Construirlo exige leer la
# descripción de cada proyecto de Azure DevOps.
MSP_QA_CATALOG_TTL_SECONDS = int(
    (
        os.getenv(
            "MSP_QA_CATALOG_TTL_SECONDS",
            "1800",
        )
        or "1800"
    ).strip()
)

if MSP_QA_CATALOG_TTL_SECONDS <= 0:
    raise ValueError(
        "MSP_QA_CATALOG_TTL_SECONDS debe ser mayor que cero."
    )

# Vigencia de una vista previa en caché. Al escribir se reutilizan sus
# filas para no volver a consultar Azure DevOps.
MSP_QA_PREVIEW_TTL_SECONDS = int(
    (
        os.getenv(
            "MSP_QA_PREVIEW_TTL_SECONDS",
            "1800",
        )
        or "1800"
    ).strip()
)

if MSP_QA_PREVIEW_TTL_SECONDS <= 0:
    raise ValueError(
        "MSP_QA_PREVIEW_TTL_SECONDS debe ser mayor que cero."
    )

# Archivo y pestaña donde vive la configuración de la matriz. El
# identificador del archivo no puede estar en la propia hoja: hace
# falta para poder abrirla.
MSP_QA_SPREADSHEET_ID = os.getenv(
    "MSP_QA_SPREADSHEET_ID",
    "",
).strip()

MSP_QA_CONFIG_SHEET = os.getenv(
    "MSP_QA_CONFIG_SHEET",
    "Config",
).strip()

MSP_QA_CONFIG_TTL_SECONDS = int(
    (
        os.getenv(
            "MSP_QA_CONFIG_TTL_SECONDS",
            "60",
        )
        or "60"
    ).strip()
)

if MSP_QA_CONFIG_TTL_SECONDS <= 0:
    raise ValueError(
        "MSP_QA_CONFIG_TTL_SECONDS debe ser mayor que cero."
    )
